### ISSUE TITLE
episilon issue

### ISSUE THREAD

**Issue by yuvateja3400** [PratikSavla/compiler-design-lab#2]
how do we include epsilon in removing recursion?

**Comment by PratikSavla** [comment]
Currently Ex.3 file doesn't support epsilon. If you can make a pull request with the addition of that feature I'll merge it after verification.

**Comment by yuvateja3400** [comment]
Ohh okay cool
Actually I had a project evaluation on LL(1)  in a week could you please
have a look on it
Or else please send me the code for left factoring

**Comment by yuvateja3400** [comment]
The code which you have removed for left factoring
